<style>
    p {
        font-family: Georgia, sans-serif;
        font-size: 14px;
        line-height: 20px;
        margin-bottom: 20px;
        text-align: justify
    }
</style>

<div class="container_16">
    <div class="grid_12 prefix_2">

        <p><b>Portuga.pl</b> jest dla Ciebie, ale polega równiez na Tobie. Zasada jest prosta:
            jeżeli szukasz tłumaczenia pomiędzy językami polskim i portugalskim,
            to wpisz znane Ci słowo w pole wyszukiwania i wciśnij Przetłumacz.
            Jeżeli znalezione słowo Ci odpowiada - wciśnij link [ OK ] znajdujący się obok tłumaczenia -
            pozwoli to Portkowi wyselekcjonować te najtrafniejsze. Jeżeli sądzisz, że można dane słowo
            przetłumaczyć trafniej - kliknij link "podaj własne tłumaczenie". Po wypełnieniu formularza
            (z lewej słowo w języku polskim, z prawej - portugalskim) rozwiąż test
            <a href="http://pl.wikipedia.org/wiki/Captcha" target="_blank">captcha</a> i wciśnij "Zapisz".
            Twoja wersja wyląduje u nas w bazie :)</p>

        <p>Dodatkową funkcją jest możliwość odsłuchania słowa czytanego przez lektorkę ;)
            Wystarczy jedynie kliknąć w link z portugalskim tłumaczeniem.</p>

        <p>Możesz umieścić Portka na swojej stronie. W tym celu umieść tam kod html:
        <pre>&lt;iframe src="http://portuga.pl/embed"&gt;&lt;/iframe&gt;</pre></p>

        <p>Efekt będzie następujący:</p>

        <iframe src="http://portuga.pl/embed" style="width: 400px; height: 200px; border: 1px"></iframe>

        <p>Przewidywana jest wersja w języku portugalskim</p>

        <p><b>Portuga.pl</b> to serwisik, który powstał z nudów i chęci spróbowania zmierzenia się
            z zagadnieniem wykorzystania API translate udostępnianego przez Google. Polega na funkcjonowaniu
            zewnętrznego oprogramowania, więc może przyjść moment, w którym nastąpi ograniczenie lub zmiana
            funkcjonalności. Nie jest i nie będzie komercyjny. Zastrzegam sobie prawo do zmian oraz usunięcia serwisu
            bez powiadamiania kogokolwiek. Nie ponoszę odpowiedzialności za straty spowodowane używaniem
            serwisu - używasz go na własną odpowiedzialność. Większość funkcji została przetestowana
            i na moment obecny działa ok, ale możliwe są uchybienia w procesie testowania.</p>

        <p>Autorem i administratorem <b>Portuga.pl</b> jest Grzegorz 'Uirapuru' Kaszuba</p>
    </div>
</div>